### ISSUE TITLE
Replying an email doesn't mark it as replied

### ISSUE THREAD

**Issue by lyz-code** [pimalaya/himalaya#508]
When using the command line tool to reply an email, for example `himalaya messages reply 245`, the message `245` is not marked as replied once the reply has been sent if it's seen through the report `himalaya envelopes list`

**Comment by soywod** [comment]
Fixed on `master`, thank you reporting the bug!

**Comment by lyz-code** [comment]
I've checked that it's solved if used from the command line. However if I use the vim plugin it's not solved. Do you know why might this be happening?

**Comment by soywod** [comment]
Yes, from the Vim (and Emacs) plugin it can only send raw messages, there is no notion of repyling of forwarding. It needs to be done manually plugin side. But it used to work, so sth may have been broken elsewhere.
